# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 2.1.0
maven_group = mc.quackedducks
archives_name = quack

# Minecraft properties
minecraft_version = 1.21.1

# NeoForm (for common module - ModDevGradle)
neoform_version = 1.21.1-20240808.144430

# Dependencies
fabric_loader_version = 0.19.3
fabric_api_version = 0.116.13+1.21.1
neoforge_version = 21.1.235
geckolib_version = 4.9.2
