modLoader = "javafml"
loaderVersion = "[9,)"
#issueTrackerURL = "https://github.com/rvhoyos/QuackMod/issues"
license = "All Rights Reserved"

[[mods]]
modId = "quack"
version = "${version}"
displayName = "QuackedDucks"
authors = "rvhoyos"
description = '''
New duck entity with custom items such as meat, cooked meat, foie gras with buffs and custom Duck AI behavior on land and water (flying coming soon!)
'''
logoFile = "icon.png"


[[dependencies.quack]]
modId = "neoforge"
type = "required"
versionRange = "[21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quack]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quack]]
modId = "architectury"
type = "required"
versionRange = "[17.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "quack.mixins.json"
